temp_dir: C:\WINRM\

office_retries: 600

NVIDIA_GPU: true

git_user_name: Joshua Haupt
git_user_email: joshua@hauptj.com


#win_update_categories:
#  - CriticalUpdates
#  - DefinitionUpdates
#  - SecurityUpdates
#  - Updates
