---
  # Installs magical cloud things

- name: Copy devmode.ps1
  win_copy:
    src: files/devmode.ps1
    dest: "{{ temp_dir }}"

- name: Execute devmode.ps1
  win_shell: powershell -ExecutionPolicy Unrestricted -File "{{ temp_dir }}devmode.ps1"

- name: Reboot since required
  win_reboot:
      reboot_timeout_sec: 3600
      connect_timeout_sec: 3600
      shutdown_timeout_sec: 3600
