---
  # Installs magical cloud things

- name: Copy devmode.ps1
  win_copy:
    src: files/devmode.ps1
    dest: "{{ temp_dir }}"

- name: Execute devmode.ps1
  win_shell: powershell -ExecutionPolicy Unrestricted -File "{{ temp_dir }}devmode.ps1"

- name: Reboot since required
  win_reboot:
      reboot_timeout_sec: 3600
      connect_timeout_sec: 3600
      shutdown_timeout_sec: 3600

- name: Install the latest and greatest container tools
  win_chocolatey:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker-for-windows
    - docker-compose
    - kubernetes-cli
    - minikube
    - kubernetes-kompose
    - kubernetes-helm

# This may break kubernetes-cli???
- name: Install the latest version of Google Cloud SDK
  win_chocolatey:
    name: gcloudsdk
    state: latest
  when: GCLOUD == true

- name: Install the latest and greatest HashiCorp utilities
  win_chocolatey:
    name: "{{ item }}"
    state: latest
  with_items:
    - vagrant
    - packer
    - terraform
    - vault

- name: Install the OpenStack CLI
  win_command: pip install python-openstackclient

- name: Install the AWS CLI
  win_command: pip install awscli

- name: Install CloudFlare API
  win_command: pip install cloudflare

- name: Install Digitalocean Python API
  win_command: pip install dopy

- name: Download Ansible Docker
  win_shell: docker pull hauptj/ansible-fedora-27
  args:
    chdir: "{{ temp_dir }}"
  ignore_errors: True
