---
- name: Provisions Windows 10 Environment
  hosts: windows
  strategy: debug
  ignore_errors: True
#  become: yes
#  become_method: runas
#  become_user: Administrator

  roles:
    - initialize
    - libraries
    - tools
    - editors
    - browsers
    - cloud
    - git
    - office
    - finalize
