---
  # Tasks to download and install MS Office and Visio
  # TODO: Actually installing MS Office and Visio

- name: Download Visio 2016
  win_get_url:
    url: https://officecdn.microsoft.com/db/492350F6-3A01-4F97-B9C0-C7C6DDF67D60/media/en-US/VisioProRetail.img
    dest: "{{ temp_dir }}VisioProRetail.img"
  async: 1000
  poll: 0
  register: visio_sleeper

- name: check on office download
  async_status: jid={{ visio_sleeper.ansible_job_id }}
  register: job_result
  until: job_result.finished
  retries: "{{ office_retries }}"

- name: Download Office 365 2016
  win_get_url:
    url: https://officecdn.microsoft.com/db/492350F6-3A01-4F97-B9C0-C7C6DDF67D60/media/en-US/O365ProPlusRetail.img
    dest: "{{ temp_dir }}O365ProPlusRetail.img"
  async: 1000
  poll: 0
  register: office_sleeper

- name: check on office download
  async_status: jid={{ office_sleeper.ansible_job_id }}
  register: job_result
  until: job_result.finished
  retries: "{{ office_retries }}"
