---
  # Installs various tools and utilities

- name: Install the latest version of openssh
  win_chocolatey:
    name: openssh
    state: latest
    params: SSHAgentFeature

- name: Install the latest version of Spotify
  win_chocolatey:
    name: spotify
    state: latest
    ignore_checksums: yes

- name: Install the latest version of HexChat
  win_chocolatey:
    name: hexchat
    state: latest

- name: Install the latest version of Steam
  win_chocolatey:
    name: steam
    state: latest
