---
  # Installs various tools and utilities

- name: Install the latest version of openssh
  win_chocolatey:
    name: openssh
    state: latest
    params: SSHAgentFeature

# - name: Install the latest version of cmder
#   win_chocolatey:
#     name: cmder
#     state: latest
#
# - name: Install the latest version of conemu
#   win_chocolatey:
#     name: conemu
#     state: latest
#
# - name: Install the latest version of winsshterm
#   block:
#     - name: Install the latest version of winsshterm
#       win_chocolatey:
#         name: winsshterm
#         state: latest
#
#     - name: Copy required executables for WinSSHTerm to {{ temp_dir }}
#       win_copy:
#         src: winsshterm/
#         dest: "{{ temp_dir }}"

- name: Install the latest version of curl
  win_chocolatey:
    name: curl
    state: latest

- name: Install the latest version of wget
  win_chocolatey:
    name: wget
    state: latest

- name: Install the latest version of heidisql
  win_chocolatey:
    name: heidisql
    state: latest

- name: Install the latest PDF Utilites
  win_chocolatey:
    name: "{{ item }}"
    state: latest
  with_items:
    - sumatrapdf.install
    - pdfcreator

- name: Install the latest version of calibre
  win_chocolatey:
    name: calibre
    state: latest

- name: Install the latest version of foobar2000
  win_chocolatey:
    name: foobar2000
    state: latest

- name: Install the latest version of Spotify
  win_chocolatey:
    name: spotify
    state: latest
    ignore_checksums: yes

- name: Install the latest and greatest Video tools
  win_chocolatey:
    name: "{{ item }}"
    state: latest
  with_items:
    - ffmpeg
    - winff
    - openshot
    - activepresenter
    - k-litecodecpackmega
    - vlc

- name: Install the latest and greatest Image tools
  win_chocolatey:
    name: "{{ item }}"
    state: latest
  with_items:
    - imagemagick
    - greenshot
    - gimp
    - irfanview
    - irfanviewplugins

- name: Install the latest version of HexChat
  win_chocolatey:
    name: hexchat
    state: latest

- name: Install the latest version of Steam
  win_chocolatey:
    name: steam
    state: latest

- name: Install the latest version of Teamviewer
  win_chocolatey:
    name: teamviewer
    state: latest

- name: Install the latest version of Skype
  win_chocolatey:
    name: skype
    state: latest
